prometheus-community/pgbouncer_exporter

VERSION
pgbouncer_exporter.go

Like all official exporters, we should migrate to `kingpin` as well, for flag management.
>**Note**, this is breaking change, all flags now must be prefixed with double dash (`--`)

Switch to kingpin for flag handling and enable log flags

---

collector.go

This change fixes a panic when encountering an invalid label value.
The previous fix added an additional nonfatal error for non-UTF8 strings, but still attempted to persist the metric with the invalid label. 
This replaces the invalid value with `<invalid>`. Having deployed this change into a production environment, it was still helpful to know the other label values, so I prefer this solution to not persisting the series, which is an alternative solution.

Fix for invalid labels

---

collector.go

pgbouncer doesn't support the standard lib/pq `db.Ping()`. Use "SHOW
STATS" intead.

Use custom db.Ping() method

---

collector.go

Without this, pgbouncer exporter- when ran against a long running high
thoroughput pgbouncer instance- can stop reporting all database stats
due to the internal scanner failing to do conversions to 64bit ints.
Without this check, those errors are completely lost; this doesn't fix
issue #10, but it does fix the bug that was hiding the failure.

Add missing rows.Err() check to detect rows.Scan failures

---

.promu.yml
Makefile.common
VERSION
collector.go
pgbouncer_exporter.go

* Add exporter build info metric.
* Add pgbouncer version info metric.
* Update Makefile.common.
* Fix path to version embedding in promu config.
* Make scrape errors non-fatal.
Signed-off-by: Ben Kochie <superq@gmail.com>

Add info metrics

---

collector.go

The problem is that we never show database query errors, because we
panic before we show the error message.
The fix is to defer closing the rows after we checked that there was no
error querying the database.

fix: do not panic closing nil rows

---

collector.go

The problem is that some metrics in the stats namespace are always
wrong: either unit counters are multiplied by 1e6, or millisecond
counters are NOT multiplied by 1e6. The reason is that if two metrics in
the same namespace have different values for the factor field, one of
these values is being chosen randomly in NewExporter and used for all
metrics.
That's because we range over a map and use values in a closure inside
the range loop.
The fix is to declare a variable inside the range loop.

fix: fix conversion function litteral

---

collector.go

If we get 3 errors after doing the 3 queries `SHOW DATABASE`, `SHOW
STATS` and `SHOW POOLS`, set the up gauge to 0. Otherwise, we were able
to talk to pgbouncer so set the up gauge to 1.

fix: set the up gauge to 1

---

collector.go

As reported in https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/9966#note_333208743, a `[]byte` value was not being converted, which can happen with numeric types.

Fix byte slice values not receiving conversion factor

---

CHANGELOG.md
pgbouncer_exporter.go

Add an option to pass a pgboucner PID file into the exporter to collect
process metrics.
Closes: https://github.com/prometheus-community/pgbouncer_exporter/issues/26
Signed-off-by: Ben Kochie <superq@gmail.com>

Add pgbouncer process metrics

---

CHANGELOG.md
collector.go
struct.go

* Remove scrape counter, covered by promhttp metrics.
* Combine up and error metrics to simplify use.
* Remove scrape duration counter, covered by `scrape_duration_seconds`.
* Use Const metric for `up` metric.
Signed-off-by: Ben Kochie <superq@gmail.com>

Cleanup exporter metrics

---

CHANGELOG.md
collector.go

* `pgbouncer_stats_queries_duration_seconds` -> `pgbouncer_stats_queries_duration_seconds_total`
* `pgbouncer_stats_client_wait_seconds` -> `pgbouncer_stats_client_wait_seconds_total`
* `pgbouncer_stats_server_in_transaction_seconds` -> `pgbouncer_stats_server_in_transaction_seconds_total`
Signed-off-by: Ben Kochie <superq@gmail.com>

Update counter metric names

---

pgbouncer_exporter.go

Rename  log: Starting stackdriver_exporter to pgbouncer_exporter
Fix #49

rename starting log msg

---

README.md

In https://github.com/prometheus-community/pgbouncer_exporter/pull/35 the counter metric names were updated to match conventions, which has
been released in v0.4.0.
This change brings the README in line with that.
Signed-off-by: Ben Wheatley <contact@benwh.com>

Update metric names in README

---

collector.go

Drop the extra colon.
Closes #66

Fix typo in reserve_pool metric

---

README.md
collector.go

Config metrics are not currently not exposed
by the exporter. These metrics are used in some
existing dashboards.
Config metrics being exposed:
- max_client_conn: pgbouncer_config_max_client_conn
- max_user_connections: pgbouncer_config_max_user_connections
Signed-off-by: kenneth-duffel <93927344+kenneth-duffel@users.noreply.github.com>

Expose config metrics

---

pgbouncer_exporter.go

For the custom commandline options environment variable handling is added. Especially the connection string comes in handy if using the exporter via container deployment so that no credentials or otherwise sensible information is visible in the commandline or process list.

Add environment variable handling

---

pgbouncer_exporter.go

For the connection option environment variable handling is added. The connection string comes in handy if using the exporter via container deployment so that no credentials or otherwise sensible information is visible in the commandline or process list.
As discussed in #132 I dropped the additional handling of `PGBOUNCER_EXPORTER_PIDFILE_PATH` and `PGBOUNCER_EXPORTER_METRICS_PATH`.

Allow connection config via environment variable

---

collector.go

Collects auth type as a gauge to track the types of auth used across a fleet of pgbouncers (useful for migrations from md5 -> scram for example)

Add new auth_type collector

---

collector.go

The `auth_type` has non-float values like `md5` which breaks the exporter here: https://github.com/prometheus-community/pgbouncer_exporter/blob/a37997d64438360e7dc2e8d8b7f9064c2b176e13/collector.go#L228
Also fixes https://github.com/prometheus-community/pgbouncer_exporter/issues/172

Revert auth_type guage
